apiVersion: apps/v1
kind: Deployment
metadata:
  name: step-tracker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: step-tracker
  template:
    metadata:
      labels:
        app: step-tracker
    spec:
      containers:
      - name: step-tracker
        image: kvnbbg/step-tracker:latest
        ports:
        - containerPort: 8080
        - containerPort: 9090  # Exposing Prometheus port
    readinessProbe:
      httpGet:
        path: /actuator/prometheus
        port: 9090
      initialDelaySeconds: 5
      periodSeconds: 10
